### PR TITLE
Improve coverage for accounts tests

### LINKED ISSUE #3: Add more tests for accounts
## Motivation
The current test cases for accounts / user profile coverage is only 76%. I think we can do better by adding more test.

Example: 
https://github.com/Kindev/fundraisee-api/blob/ca93370ec08f1e3c6fc49043ed8f311327a48d12/accounts/tests.py#L7-L27

### PR DESCRIPTION
**Pull request by fiennyangeln**
## Motivation

Closes #3 

## Test Plan

Run tests account

### CODE REVIEW

**Comment by endiliey** [comment]
Oops .. Test is failing. Can you push a fix @fiennyangeln ? 😄

**Comment by michjk** [comment]
The branch is not up to date with current master branch.

**Comment by fiennyangeln** [comment]
haha sorry!

**Comment by endiliey** [comment]
@fiennyangeln I was patching your PR actually. Seems that you disallow 'edit from maintainers' 😢 

By the way it would be nice to use merge rather than rebase because if you rebase then I won't be able to see the subsequent changes in commit & have to review the code all over again.

**Pull request merged**
